# Archype: black with Arch Linux blue

[colors-dark]
background=000000
foreground=d0d0d0
cursor=000000 1793d1

regular0=1c1c1c
regular1=e05561
regular2=8cc265
regular3=d9a74a
regular4=1793d1
regular5=b57edc
regular6=42b3c2
regular7=b0b0b0

bright0=4d4d4d
bright1=ff6b76
bright2=a5dc7f
bright3=f0c060
bright4=4fb3e8
bright5=cc99ee
bright6=5fd0de
bright7=ffffff

selection-background=1793d1
selection-foreground=000000
